export const ROUTES = {
  DASHBOARD: '/',
  BUSINESS: '/business',
  COMEDY: '/comedy',
  SPORTS: '/sports',
  NEWS: '/news',
  CHARTS: '/charts',
  ENTERTAINMENT: '/entertainment',
  MUSIC: '/music',
  CULTURE: '/culture',
  RELATIONSHIPS: '/relationships',
  MENTAL_HEALTH: '/mental-health',
  LEISURE: '/leisure',
  CATEGORY: '/category',
  VIDEO_PLAYER: '/video-player',
  PODCAST_VIDEO_PLAYER: '/podcast-video-player',
  HIGHLIGHTED_PODCASTS: '/highlighted-podcasts',
  SAVED: '/saved',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  LEGAL: '/legal',
  TEAM: '/team',
  CONTACT: '/contact',
  BLOG: '/blog',
  ABOUT: '/about',
  UPDATE_PROFILE: '/update-profile',
  VIEW_PROFILE: '/view-profile',
  VERIFY_PROFILE: '/verify-profile',
  PRO_PLAN: '/verify-profile/pro-plan',
  SETTINGS: '/settings',
  PASSWORD: '/password',
  MANAGE_SESSIONS: '/manage-sessions',
  MOBILE_APP: '/view-app',
};

export const PUBLIC_ROUTES = {
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  SET_NEW_PASSWORD: '/set-new-password',
};
